import { hash, Keypair, Networks, xdr } from '@stellar/stellar-sdk';
import { SCPStatement, verifySCPEnvelopeSignature } from '../src';

// Captured with the deployed SDK 16.2.0, not regenerated by this test. Covers
// unsigned-64 precision and binary values whose UTF-8 interpretation is lossy.
const statementBytes =
	'AAAAAOpKbGPinFIKvvVQexMuxfmVR3auvr57kkIe6mkURtIs//////////8AAAACAAAACQAAAAQAgP8BAAAADAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI';
const messageBytes =
	'AAAACwAAAADqSmxj4pxSCr71UHsTLsX5lUd2rr6+e5JCHuppFEbSLP//////////AAAAAgAAAAkAAAAEAID/AQAAAAwICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAAAAEBnLcO3CRtOoXKjxs6z4+TMrHR0J5uEJLIRYmbsZTGK7Rm5/iqoadXBbewRmHs9P+HEsRBY7jq3AYYVwPiZMn8K';
const signatureHex =
	'672dc3b7091b4ea172a3c6ceb3e3e4ccac7474279b8424b2116266ec65318aed19b9fe2aa869d5c16dec11987b3d3fe1c4b11058ee3ab7018615c0f899327f0a';

it('preserves SDK16 SCP bytes, signature preimage and persisted DTO encodings', () => {
	const message = xdr.StellarMessage.fromXdr(messageBytes, 'base64');
	if (message.type !== 'scpMessage') throw new Error('Expected SCP fixture');
	expect(message.toXdr('base64')).toBe(messageBytes);
	expect(message.envelope.statement.toXdr('base64')).toBe(statementBytes);
	expect(
		Buffer.from(message.envelope.signature.toBytes()).toString('hex')
	).toBe(signatureHex);
	const network = Buffer.from(hash(Buffer.from(Networks.PUBLIC)));
	const verification = verifySCPEnvelopeSignature(message.envelope, network);
	expect(verification.isOk() && verification.value).toBe(true);
	const key = Keypair.fromRawEd25519Seed(Buffer.alloc(32, 7));
	const preimage = Buffer.concat([
		network,
		Buffer.from([0, 0, 0, 1]),
		message.envelope.statement.toXdr()
	]);
	expect(Buffer.from(key.sign(preimage)).toString('hex')).toBe(signatureHex);
	const dto = SCPStatement.fromXdr(statementBytes);
	expect(dto.isOk()).toBe(true);
	if (dto.isErr()) throw dto.error;
	expect(dto.value).toMatchObject({
		nodeId: 'GDVEU3DD4KOFECV66VIHWEZOYX4ZKR3WV27L464SIIPOU2IUI3JCZA57',
		slotIndex: '18446744073709551615',
		type: 'externalize',
		pledges: {
			nH: 12,
			commit: { counter: 9, value: 'AID/AQ==' },
			quorumSetHash: Buffer.alloc(32, 8).toString('base64')
		}
	});
});
