data_directory = '/mnt/bulk/stellarbeat-data/postgresql/16/main'
hba_file = '/etc/postgresql/16/stellaratlas/pg_hba.conf'
ident_file = '/etc/postgresql/16/stellaratlas/pg_ident.conf'
external_pid_file = '/run/stellaratlas-postgresql/external.pid'
listen_addresses = '192.168.1.153'
port = 55432
unix_socket_directories = '/run/stellaratlas-postgresql'
ssl = off
cluster_name = 'stellaratlas'
