apiVersion: v1
kind: Namespace
metadata:
  name: stellaratlas
  labels:
    name: stellaratlas
    app.kubernetes.io/name: stellaratlas
    app.kubernetes.io/part-of: stellaratlas
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stellaratlas-quota
  namespace: stellaratlas
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: stellaratlas-limits
  namespace: stellaratlas
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container