apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: stellaratlas
  labels:
    app.kubernetes.io/name: users-service
    app.kubernetes.io/component: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users-service
      app.kubernetes.io/component: users
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-service
        app.kubernetes.io/component: users
    spec:
      containers:
      - name: users-service
        image: stellaratlas/users-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: stellaratlas-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: stellaratlas-config
              key: LOG_LEVEL
        - name: USERS_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: stellaratlas-config
              key: USERS_SERVICE_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: stellaratlas-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: stellaratlas-secrets
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: stellaratlas-secrets
              key: SESSION_SECRET
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-service -p 5432 -U stellaratlas_user; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: stellaratlas
  labels:
    app.kubernetes.io/name: users-service
    app.kubernetes.io/component: users
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: users-service
    app.kubernetes.io/component: users